version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."

  build:
    commands:
      - echo "Building Docker image..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v9g5c6v3/hello-world
      - docker build -t hello-world .
      - docker tag hello-world:latest public.ecr.aws/v9g5c6v3/hello-world:latest
      - docker push public.ecr.aws/v9g5c6v3/hello-world:latest
