version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REGISTRY_URL/your-ecr-repo:latest .
      - docker push $ECR_REGISTRY_URL/your-ecr-repo:latest

